name: PrimeiroPainel

options:
  bundleIdPrefix: com.jonatas

targets:
  PrimeiroPainel:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - ContentView.swift
      - PrimeiroPainelApp.swift

    info:
      path: Info.plist

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jonatas.primeiropainel
        SWIFT_VERSION: 5.0
